### ISSUE TITLE
Non-observables passed to when()

### ISSUE THREAD

**Issue by christianbundy** [arj03/patch-book#1]
Heyo! I've configured `when()` to throw a stack trace when we're (ab)using it on non-observables, so I just wanted to document them in an issue. This isn't creating any errors, but it may be doing something different than what we want. I've been replacing `when(a, b, c)` with`a ? b : c` locally.

```
Trace: Non-observable passed to when()
    at When (/home/christianbundy/Source/patchbay/node_modules/mutant/when.js:9:13)
    at title (/home/christianbundy/Source/patchbay/node_modules/patch-gatherings/gathering/html/title.js:16:7)
    at /home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30
    at Object.gatheringLayout (/home/christianbundy/Source/patchbay/node_modules/patch-gatherings/gathering/html/layout/card.js:50:9)
    at Object.layout (/home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30)
    at Object.renderGathering (/home/christianbundy/Source/patchbay/node_modules/patch-gatherings/gathering/html/render.js:45:28)
    at Object.render (/home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30)
    at render (/home/christianbundy/Source/patchbay/app/page/public.js:67:33)
    at add (/home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:42:15)
    at HTMLDivElement.scroll (/home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:50:7)

Trace: Non-observable passed to when()
    at When (/home/christianbundy/Source/patchbay/node_modules/mutant/when.js:9:13)
    at description (/home/christianbundy/Source/patchbay/node_modules/patch-gatherings/gathering/html/description.js:17:7)
    at /home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30
    at Object.gatheringLayout (/home/christianbundy/Source/patchbay/node_modules/patch-gatherings/gathering/html/layout/card.js:51:9)
    at Object.layout (/home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30)
    at Object.renderGathering (/home/christianbundy/Source/patchbay/node_modules/patch-gatherings/gathering/html/render.js:45:28)
    at Object.render (/home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30)
    at render (/home/christianbundy/Source/patchbay/app/page/public.js:67:33)
    at add (/home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:42:15)
    at HTMLDivElement.scroll (/home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:50:7)

Trace: Non-observable passed to when()
    at When (/home/christianbundy/Source/patchbay/node_modules/mutant/when.js:9:13)
    at images (/home/christianbundy/Source/patchbay/node_modules/patch-book/book/html/images.js:20:7)
    at /home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30
    at Object.bookLayout (/home/christianbundy/Source/patchbay/node_modules/patch-book/book/html/layout/card.js:56:9)
    at Object.layout (/home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30)
    at renderBook (/home/christianbundy/Source/patchbay/node_modules/patch-book/book/html/render.js:45:23)
    at /home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30
    at add (/home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:42:15)
    at /home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:71:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at check (/home/christianbundy/Source/patchbay/node_modules/pull-many/index.js:72:16)
    at next (/home/christianbundy/Source/patchbay/node_modules/pull-many/index.js:110:5)
    at read (/home/christianbundy/Source/patchbay/node_modules/pull-many/index.js:114:40)
    at next (/home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:14:9)

Trace: Non-observable passed to when()
    at When (/home/christianbundy/Source/patchbay/node_modules/mutant/when.js:9:13)
    at series (/home/christianbundy/Source/patchbay/node_modules/patch-book/book/html/series.js:17:7)
    at /home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30
    at Object.bookLayout (/home/christianbundy/Source/patchbay/node_modules/patch-book/book/html/layout/card.js:59:11)
    at Object.layout (/home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30)
    at renderBook (/home/christianbundy/Source/patchbay/node_modules/patch-book/book/html/render.js:45:23)
    at /home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30
    at add (/home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:42:15)
    at /home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:71:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at check (/home/christianbundy/Source/patchbay/node_modules/pull-many/index.js:72:16)
    at next (/home/christianbundy/Source/patchbay/node_modules/pull-many/index.js:110:5)
    at read (/home/christianbundy/Source/patchbay/node_modules/pull-many/index.js:114:40)
    at next (/home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:14:9)

Trace: Non-observable passed to when()
    at When (/home/christianbundy/Source/patchbay/node_modules/mutant/when.js:9:13)
    at series (/home/christianbundy/Source/patchbay/node_modules/patch-book/book/html/series.js:30:7)
    at /home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30
    at Object.bookLayout (/home/christianbundy/Source/patchbay/node_modules/patch-book/book/html/layout/card.js:59:11)
    at Object.layout (/home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30)
    at renderBook (/home/christianbundy/Source/patchbay/node_modules/patch-book/book/html/render.js:45:23)
    at /home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30
    at add (/home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:42:15)
    at /home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:71:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at check (/home/christianbundy/Source/patchbay/node_modules/pull-many/index.js:72:16)
    at next (/home/christianbundy/Source/patchbay/node_modules/pull-many/index.js:110:5)
    at read (/home/christianbundy/Source/patchbay/node_modules/pull-many/index.js:114:40)
    at next (/home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:14:9)

Trace: Non-observable passed to when()
    at When (/home/christianbundy/Source/patchbay/node_modules/mutant/when.js:9:13)
    at authors (/home/christianbundy/Source/patchbay/node_modules/patch-book/book/html/authors.js:17:7)
    at /home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30
    at Object.bookLayout (/home/christianbundy/Source/patchbay/node_modules/patch-book/book/html/layout/card.js:60:11)
    at Object.layout (/home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30)
    at renderBook (/home/christianbundy/Source/patchbay/node_modules/patch-book/book/html/render.js:45:23)
    at /home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30
    at add (/home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:42:15)
    at /home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:71:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at check (/home/christianbundy/Source/patchbay/node_modules/pull-many/index.js:72:16)
    at next (/home/christianbundy/Source/patchbay/node_modules/pull-many/index.js:110:5)
    at read (/home/christianbundy/Source/patchbay/node_modules/pull-many/index.js:114:40)
    at next (/home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:14:9)
```

**Comment by arj03** [comment]
Hmm @christianbundy . I looked at the first one, which should be:

https://github.com/arj03/patch-book/blob/master/book/html/images.js#L20

isEditing is an observable. So is it because you are also checking if the other arguments are observables?

**Comment by christianbundy** [comment]
Weird, I wonder why. My only change was patching `node_modules/mutant/when.js` from [this](https://github.com/mmckegg/mutant/blob/4cc5d7c35493700dc9a40f3cb6da6a2b6e3ce7dc/when.js#L6-L10) to:

```js
function When (obs, ifTrue, ifFalse) {
  // <change>
  if (!isObservable(obs)) {
    console.trace('Non-observable passed to when()')
    return obs ? ifTrue : ifFalse
  }
  // </change>

  ifTrue = handleInnerValues(ifTrue)
  ifFalse = handleInnerValues(ifFalse)
  return computed([obs, ifTrue, ifFalse], lambda)
}
```

I'm not sure why, but at least for me `!isObservable(obs)` is, at some point, truthy. The code *shouldn't* be checking the other arguments, but I wouldn't be surprised if I'm doing something wrong. Btw, here's some context for that code on SSB:

```
%DGNcew0sluWW4zDJtq85lb7Ue6HftToMosePrAi5tf0=.sha256
```
